### PR TITLE
[PowerShell] add PowerShell-Beautifier.

### PR DESCRIPTION
**Pull request by ssfjhh**
Add PowerShell-Beautifier.

### CODE REVIEW

**Comment by sbdchd** [comment]
looks good

Can you also update `docs/Neoformat.txt`?

**Comment by ssfjhh** [comment]
I have updated `docs/neoformat.txt`. Is that OK enough?
It seems that there is a resemblance between `Readme.md` and `neoformat.txt`. Why you keep the two different files?

**Comment by sbdchd** [comment]
Never got around to writing a converter

`neoformat.txt` is for docs in vim, `README.md` is for docs in the repo

**Comment by sbdchd** [comment]
Thanks!

**Pull request merged**
