### PR TITLE
feat: add blade-formatter

### PR DESCRIPTION
**Pull request by mjbrownie**
Handler for blade templates (used in the Laravel framework)

https://github.com/shufo/blade-formatter

### CODE REVIEW

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
Thanks!

**Comment by jesseleite** [comment]
Hey @mjbrownie, I don't see blade as a supported filetype in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). Curious how you're doing your filetype and syntax highlighting for blade files atm?

**Comment by mjbrownie** [comment]
hi @jesseleite yeah I've been waiting on a parser.  I just installed the old vim-blade plugin which is ok for me (predominantly api coding atm),  but would like more text object motions in the future.

 `use 'jwalton512/vim-blade'`

Randomly saw this the other day but the poster was light on links / context... pehaps message them?

https://www.reddit.com/r/neovim/comments/vxhr0g/treesitter_on_laravel_blade_is_awesome/

**Comment by jesseleite** [comment]
@mjbrownie Ah gotcha. Thanks!

**Pull request merged**
