### PR TITLE
Add jq as JSON formatter

### PR DESCRIPTION
**Pull request by epeli**
https://stedolan.github.io/jq/

Available in Ubuntu & Debian repositories too.

### CODE REVIEW

**Comment by sbdchd** [comment]
Looks good.

Is passing `.` as an arg necessary?

Also, can you update the `README.md` and `docs/neoformat.txt` as well?

Thanks!

**Comment by epeli** [comment]
> Is passing . as an arg necessary?

Yes. The first arg is the jq selector and `.` just means select the whole object.

> Also, can you update the README.md and docs/neoformat.txt as well?

Will do!

**Comment by epeli** [comment]
Commit rebased with the doc updates.

**Comment by sbdchd** [comment]
Thanks!

**Pull request merged**
