### PR TITLE
Add 'prettier' support for css, less and scss

### PR DESCRIPTION
**Pull request by renstrom**
The 1.4.0 release of prettier added support for css, less and scss: https://github.com/prettier/prettier/releases/tag/1.4.0

I also took the liberty to fix some minor issues in the README, hope you don't mind.

### CODE REVIEW

**Comment by sbdchd** [comment]
Looks great.

Thanks!

**Comment by kevinold** [comment]
How is this now configured?  I had Vim and prettier working with prettier 1.3.1 but seems something is now broken.

This is what I had in my .vimrc against 1.3.1 and before this latest update to neoformat:

```
autocmd FileType javascript set formatprg=prettier\ --stdin
autocmd BufWritePre *.js Neoformat
```

The configuration documentation for Vim was recently updated, but does not work: https://github.com/prettier/prettier/tree/master/editors/vim#neoformat---usage

Per this commit I have also tried:

```
let g:neoformat_enabled_javascript = ['prettier']
autocmd BufWritePre *.js Neoformat
```

What is the correct syntax?

**Comment by renstrom** [comment]
Not sure why you're commenting here since this has nothing to do with formatting JavaScript. Though I guess you could try setting `let g:neoformat_verbose = 1` to see if you get some useful output.

**Comment by zhaozhiming** [comment]
I updated the latest version of neoformat and prettier, but it seems no work for formatting css.

**Comment by renstrom** [comment]
Works fine for me. Does running prettier manually work?

```
$ prettier --parser postcss foo.css
```

**Pull request merged**
