### PR TITLE
add prettier-eslint formatter

### PR DESCRIPTION
**Pull request by manveru**
This works with the https://www.npmjs.com/package/prettier-eslint-cli package, and seems to handle the eslint configuration fine.

### CODE REVIEW

**Comment by manveru** [comment]
Unfortunately this is not a fix for #51 since it also includes `prettier`, but it perfectly works for my use-case of first running `prettier` and then `eslint --fix`.

**Comment by sbdchd** [comment]
Looks good.

Could you also update the `README.md` and `doc/neoformat.txt`.

Thanks!

**Comment by manveru** [comment]
@sbdchd there you go

**Comment by sbdchd** [comment]
Thanks for the contribution!

Note: [prettier-eslint doesn't throw the correct status codes][1] for errors, which means Neoformat will input the error text into the buffer.

[1]: https://github.com/kentcdodds/prettier-eslint-cli/issues/10

**Pull request merged**
