### PR TITLE
Add prettier as a markdown formatter too

### PR DESCRIPTION
**Pull request by epeli**
See https://github.com/prettier/prettier/releases/tag/1.8.0

### CODE REVIEW

**Comment by sbdchd** [comment]
Looks good.

Could you also update the `README.md` and `docs/neoformat.txt` as well?

**Comment by maximbaz** [comment]
@epeli have you had a chance to update the docs so that this can finally be merged? 🙂

**Comment by epeli** [comment]
Oops, missed that message completely for some reason. Thanks for pinging me @maximbaz. The PR is now updated with doc updates too.

**Comment by maximbaz** [comment]
Thank you so much!

**Comment by sbdchd** [comment]
Thanks!

**Pull request merged**
