### PR TITLE
fix phpcsfixer error in php.vim

### PR DESCRIPTION
**Pull request by yech1990**

### CODE REVIEW

**Comment by codeinabox** [comment]
AFAIK the replace option is still needed as there is no support for stdin and stdout https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/454

**Comment by sbdchd** [comment]
the `replace` option can also work better in some cases where the support for `stdin` is wonky

**Comment by yech1990** [comment]
I could not run the latest php fixer with the `replace` argument, and deleting this argument can fix that problem...

**Comment by sbdchd** [comment]
@yech1990 gotcha sounds good.

**Pull request merged**
