### PR TITLE
change to directory of file to allow formatters with config files to find the corresponding config file (e.g. clang-format)

### PR DESCRIPTION
**Pull request by adrianimboden**
fixes sbdchd/neoformat#47

### CODE REVIEW

**Comment by sbdchd** [comment]
Do you think this should be behind an option flag?

I think there might be a case where a user starts up vim in a given directory with their formatting config file and then expects `:Neoformat` to be using it while they `cd` around.

**Comment by adrianimboden** [comment]
I don't think an option flag would be useful in this case. The reason is that, if you call clang-format with a file-name (as you would do in a terminal), then clang-format will ignore the working directory and use the location of the provided filename to look up the .clang-format file.

Without an option (as it would be with the patch right now), the behavior of `cd` around in vim would be the same as `cd` around in the terminal. I think that is preferable.

**Comment by shyun3** [comment]
Will this be merged?

**Review by jameswalmsley — APPROVED** [review]

**Comment by jameswalmsley** [comment]
Just like to add that without this C/C++ formatiing with clang-format is broken. We have migrated LunarVim to use this plugin, and would like to get this working..

**Comment by adrianimboden** [comment]
I'm using the patched version for years now. It is a little bit sad that the clang-format support is such a cripple without this patch on master.

@jameswalmsley if you would also test this branch for some time, maybe there is enough evidence that this patch makes no problems?

**Comment by sbdchd** [comment]
We can also revert if it turns out to have some adverse side effects

**Review by sbdchd — APPROVED** [review]
🤞🏻

**Comment by madx** [comment]
Hi,
This change breaks formatting when using formatters that are installed in a project directory v.s. installed globally. 

For example, if I install the JS formatter `prettier` using `npm i prettier` in a project, given that I have `node_modules/.bin` in my `PATH`, I am not able to use it for automatically formatting files that are in a sub-folder since it will cd in that subfolder, putting the bin path out of reach.

**Comment by sbdchd** [comment]
I've reverted this commit, thanks for the report, I was worried about something like that happening

**Comment by adrianimboden** [comment]
I find that very curious. It is just not how the .clang-format config works.
The file owner/project owner puts his config in the project folder and the files under that folder have to adhere to that style.

How in the world does opening vim in this folder correspond to this idea?

When I see the problem correctly, the correct solution would be to:
- Use the binary looked up from the current working directory
- Start it with the working directory of the current file

This way both needs would be satisfied, no?

**Pull request merged**
