### PR TITLE
Inline environment variable support

### PR DESCRIPTION
**Pull request by jfornoff**
Adds inline ENV support as discussed in #128.
Works locally for me on the example given in the issue.

My Vimscript-Fu is not super strong, so just feel free to do whatever ;-)

### CODE REVIEW

**Comment by jfornoff** [comment]
@sbdchd ping :-)

**Comment by sbdchd** [comment]
Looks good.

We should probably add a note in the docs about its usage

If I understand the usage, something like should work:

```diff
diff --git a/README.md b/README.md
index 819096b..5176511 100644
--- a/README.md
+++ b/README.md
@@ -92,6 +92,7 @@ let g:neoformat_python_autopep8 = {
             \ 'args': ['-s 4', '-E'],
             \ 'replace': 1 " replace the file, instead of updating buffer (default: 0),
             \ 'stdin': 1, " send data to stdin of formatter (default: 0)
+            \ 'env': ['DEBUG=1'], " prepend environmental variables to the exe
             \ 'no_append': 1,
             \ }
```

**Comment by jfornoff** [comment]
Done! 👍

**Comment by sbdchd** [comment]
Looks good.

Could you also update `docs/neoformat.txt`?

Thanks!

**Pull request merged**
