### PR TITLE
Reason ML support

### PR DESCRIPTION
**Pull request by lpil**
Reason is a OCaml based language from Facebook. It comes with a
formatter called `refmt`, which all all Reason code is expected to be
formatted with. This adds support for this formatter.

### CODE REVIEW

**Comment by sbdchd** [comment]
Looks good!

Could you also update the `docs/neoformat.txt` as well? Thanks.

**Comment by lpil** [comment]
Pushed an update @sd

**Comment by lpil** [comment]
The tests are failing, is that because of my changes?

**Comment by sbdchd** [comment]
The changes are great.

Test tests seem to have messed up installing `nvim`, which resulted in them failing.

**Pull request merged**
