### PR TITLE
Fix formatter (styler) error and add new formatter (formatR) for R language

### PR DESCRIPTION
**Pull request by yech1990**
Fix error in https://github.com/sbdchd/neoformat/pull/217

**To enable all the formatters, please install these R packages: `sytler`, `formatR`, `readr`.**

### CODE REVIEW

**Comment by yech1990** [comment]
To enable all the formatters, please install these R packages: `sytler`, `formatR`, `readr`.

**Comment by sbdchd** [comment]
Looks good. Thanks for fixing the readme as well!

**Comment by mimadrid** [comment]
I'm so sorry @yech1990  but now styler is not working for me 
Don't hesitate to ask for more details

> Neoformat: stderr output redirected to file/tmp/neoformat/stderr.log
> Neoformat: ['Error in read_file_(ds, locale) : ', '  Cannot read file /tmp/RtmpoxqPJt/file5f405d2ba4ed: Invalid argument', 'Calls: <Anonymous> ... transformer -> %>% -> eval -> eval -> <Anonymous> -> read_file_',
>  'Execution halted']
> Neoformat: 1
> Neoformat: trying next formatter
> Neoformat: formatters R failed to run

**Comment by yech1990** [comment]
@mimadrid  

have you installed the styler and readr package yet?
could you please run the following file in shell, and show show me the output?

```bash
cat YOUR_FILE.R| R --slave --no-restore --no-save -e "styler::style_text(readr::read_file((file(\"stdin\"))))"
```

**Comment by mimadrid** [comment]
Yes I use both package every day (also I tried to reinstall them)
cat test.R | R --slave --no-restore --no-save -e "styler::style_text(readr::read_file((file(\"stdin\"))))"
print("test")

**Comment by yech1990** [comment]
Hi @mimadrid ,

How do you load neoformat into you vim?
Would you please show me you vim config?

**Comment by mimadrid** [comment]
Hi @yech1990 I think so, neoformat is already loaded
Here you have the config 
https://github.com/mimadrid/.dotfiles/blob/master/vim/.vimrc
Thanks a lot in advance and don't hesitate to request more information or testing

**Pull request merged**
